[build]
  base = "docs"
  publish = "build"
  command = "bun run build"

[[redirects]]
  from = "/docs/*"
  to = "/docs/:splat"
  status = 200

[[headers]]
  for = "/docs/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
